
---
spring:
  config.activate.on-profile: test
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false
---
stonks:
  data:
    api:
      url: http://localhost:8080