
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false
---
stonks:
  refresh-timeout: 800000
  api:
    intraday:
      url: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&adjusted=false&symbol=${ticker}&interval=5min&apikey=${apikey}&outputsize=full
      method: GET