
---
spring:
  config.activate.on-profile: test
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false
---
stonks:
  refresh-timeout: 800000
  api:
    intraday:
      url: localhost:8080
      method: GET